<!DOCTYPE html>
<html>
    <head>
        <!-- Google Tag Manager -->
        <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-WKZ8BL9');</script>
        <!-- End Google Tag Manager -->
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width">
        <meta name="keywords" content="japanese, learning, teacher, teaching, learn, skype, nursing, language, nottingham, online, japanese teacher" />
        <meta name="Description" content="I'm Maki Cabrejas, I teach Japanese in Nottingham, United Kingdom or Online via Skype, I also teach Japanese language for Nursing professionals">
        <title>Maki Cabrejas | Japanese Tutor | Online | Nottingham, United Kingdom</title>
        <link rel="icon" type="image/png" sizes="32x32" href="/assets/img/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="96x96" href="/assets/img/favicon-96x96.png">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="/assets/css/core.css?ver=2">
        <script src="/assets/js/jquery-3.2.1.min.js"></script>
        <script src="/assets/js/jquery.validate.min.js"></script>
        <script src="/assets/js/core.js?v=1"></script>
    </head>
    <body>
        <!-- Google Tag Manager (noscript) -->
        <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WKZ8BL9"
        height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
        <!-- End Google Tag Manager (noscript) -->
        <header>
            <nav>
                <a href="#classes">Classes</a>
                <a href="#about">About</a>
                <a href="#contact">Contact</a>
            </nav>


            <?php foreach ($messages->flushMessages() as $message) : ?>
                <p class="message <?= $message['type'] ?>"><?= $message['message'] ?></p>
            <?php endforeach; ?>

            <div class="content-wrap">
                <h1>Hi! I'm a Japanese tutor</h1>
                <h2>Maki Cabrejas</h2>
                <p class="english">You can take one on one lessons on Skype or face to face if you are in Nottingham, UK.</p>
                <p class="japanese">スカイプを使っていつでもどこでも日本語のレッスンが受けられます。</p>
            </div>
        </header>

        <main>
            <!-- Section what can I offer? -->
            <section id="classes" class="offer">
                <div class="content-wrap">
                    <h2>How would you like to learn Japanese ?</h2>
                    <p>What does "learning Japanese" mean for you?<br>
                    Let me know your ideas and goals.<br>
                    Working together, lessons comply perfectly with you.</p>

                    <div class="offer-card col-left">
                        <div class="content-wrap">
                            <img class="offer-card-image" src="/assets/img/skype-icon.png" alt="Learn Japanese via Skype" />
                            <p>Enjoy learning Japanese from the comfort of your home via Skype</p>
                            <p class="tuition-fees-toggle">View Tuition fees</p>

                            <div class="tuition-fees">
                                <ul>
                                    <li>7 am to 10 pm (GMT) - &pound;20/hr</li>
                                    <li>7 am to 10 pm (GMT) - &pound;5/ 15mins</li>
                                    <li>Important to diligently and stacking !</li>
                                </ul>
                                <p>This includes lesson preparation time, all worksheets plus marking of activities completed between lessons as well as any extra advice between lessons.</p>
                            </div>
                        </div>
                    </div>

                    <div class="offer-card col-center">
                        <div class="content-wrap">
                            <img class="offer-card-image" src="/assets/img/one-to-one-icon.png" alt="Learn Japanese Face to Face in Nottingham, United Kingdom" />
                            <p>One on one class<br>In Nottingham city centre</p>
                            <p class="tuition-fees-toggle">View Tuition fees</p>

                            <div class="tuition-fees">
                                <ul>
                                    <li>7 am to 10 pm (GMT) - &pound;20/hr</li>
                                    <li>7 am to 10 pm (GMT) - &pound;5/ 15mins</li>
                                    <li>Important to diligently and stacking !</li>
                                </ul>
                                <p>This includes lesson preparation time, all worksheets plus marking of activities completed between lessons as well as any extra advice between lessons.<br>
                                    Two-to-one and three-to-one lessons are discounted.</p>
                            </div>
                        </div>
                    </div>

                    <div class="offer-card col-right">
                        <div class="content-wrap">
                            <img class="offer-card-image" src="/assets/img/medicine-icon.png" alt="Learn Japanese for nursing professionals" />
                            <p><span class="japanese">看護や介護の現場で使える日本語</span><br>Learn Japanese for nursing professionals Via Skype or Face to Face</p>
                            <p class="tuition-fees-toggle">View Tuition fees</p>

                            <div class="tuition-fees">
                                <ul>
                                    <li>7 am to 10 pm (GMT) - &pound;25/hr</li>
                                </ul>
                                <p>This includes lesson preparation time, all worksheets plus marking of activities completed between lessons as well as any extra advice between lessons.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <!-- Summary of me -->
            <section id="about" class="introduction">
                <div class="content-wrap">
                    <img class="col-narrow portrait" src="/assets/img/protrait-maki.jpg" alt="Maki Cabrejas, Japanese Tutor, Skype or Nottingham, United Kingdom" />

                    <div class="col-wide">
                        <h2>Hello, I am a Japanese Tutor and my name is <b>Maki.</b></h2>
                        <p>
                            I have completed a Postgraduate Certificate in Teaching Japanese as a Foreign Language from the International Institute of Education in London and am looking for private individual or small groups of students.
                            <br><br>
                            I help people of all ages and abilities learn Japanese for exams, holidays or business. Learning another language is such a worthwhile thing to do and can open up many doors. I find my work enjoyable and very rewarding.
                        </p>

                        <div class="twitter">
                            <a href="https://twitter.com/maki_japanese" target="_blank" alt="Learn Japanese, Why Not Japanese, Twitter">
                                <img class="twitter" src="/assets/img/twitter.png" alt="Twitter">
                            </a>
                        </div>
                    </div>
                </div>
            </section>

            <!-- Get in touch -->
            <section id="contact" class="get-in-touch">
                <div class="content-wrap">
                    <h2>Get in Touch</h2>
                    <form class="get-in-touch" method="post" action="/contact/post">
                        <input type="hidden" name="<?= $nameKey ?>" value="<?= $name ?>">
                        <input type="hidden" name="<?= $valueKey ?>" value="<?= $value ?>">
                        <span class="label">First name (required)</span><br>
                        <input name="firstname" maxlength="50" required><br>
                        <span class="label">Last name (required)</span><br>
                        <input name="lastname" maxlength="50" required><br>
                        <span class="label">Email (required)</span><br>
                        <input name="email" type="email" required><br>
                        <span class="label">Subject (required)</span><br>
                        <input name="subject" maxlength="100" required><br>
                        <span class="label">Japanese Level (required)</span><br>
                        <select name="level">
                            <option value="Complete Beginner">Complete Beginner</option>
                            <option value="Beginner">Beginner</option>
                            <option value="Intermediate">Intermediate</option>
                            <option value="Advance">Advance</option>
                        </select>
                        <span class="label">Your Message (required)</span><br>
                        <textarea id="message" name="message" required></textarea>
                        <input type="submit" value="Submit" id="input-submit">
                    </form>
                </div>
            </section>

        </main>

        <footer>
            <div class="content-wrap">
                <div class="footer-column-left">
                    <img class="logo" src="/assets/img/footer-logo.png" alt="Learn Japanese, Why Not Japanese, Logo" />
                </div>
                <div class="footer-column-center hide_mobile">
                    <p>&#169; Why Not Japanese</p>
                </div>
                <div class="footer-column-right hide_mobile">
                    <a href="https://twitter.com/maki_japanese" alt="twitter" target="_blank">
                        <img class="twitter" src="/assets/img/twitter.png" alt="Learn Japanese, Why Not Japanese, Twitter">
                    </a>
                </div>
            </div>
        </footer>
    </body>
</html>
